### ISSUE TITLE
Wintoys name is already taken, please choose another one

### ISSUE THREAD

**Issue by bogdan-patraucean** [WinTenDev/WinToys#2]
To avoid any confusion I would kindly ask you to choose a different name for your app since [Wintoys ](https://bogdan-patraucean.github.io/about/wintoys/) is already live in the Store for a year. It won't help your project either since people looking for yours would get results about mine.

**Comment by azhe403** [comment]
before starting this project, i has know that has exist. but this project just for my side time, so nothing problem when renaming this project anytime.

i will change it later

**Comment by bogdan-patraucean** [comment]
@azhe403 thanks a lot for understanding. I wish you good luck with your project. Just so you know, Google already indexed your github project when you search Wintoys, so I would appreciate if you'd be able to change at least the github repo name, as it's a few clicks effort, rather sooner than later.

Wish you a great day!
